apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-static-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-static-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-static-provisioner
          image: docker-registry.default.svc:5000/nfs-provisioners/nfs-client-static-provisioner
          env:
            - name: PROVISIONER_NAME
              value: nfs-client-static-provisioner
